### ISSUE TITLE
Invitation-Admin is in the invitation listing but if he select his user and send invitation mail not sent

### ISSUE THREAD

**Issue by Paulsurinder** [TestingReach/MVP-V1#14]
Invitation-Admin is in the invitation listing but if he select his user and send invitation mail not sent

**Comment by pankajtrantor1** [comment]
@Paulsurinder Is this not a standard reachable feature , see if you can send an invite to yourself from your own user.

**Comment by Paulsurinder** [comment]
That is already resolved, actually what happened, there is no validation message that indicate to Admin that you are already a member

**Comment by Paulsurinder** [comment]
This issue was moved to reachable-dev/Reachable-Salesforce#9
