### ISSUE TITLE
Invitation-User send invite to any user, checkbox will be uncheck after sending invitation so that if user try to send invitation to other users, it will not block invitation due to 24 hrs condition

### ISSUE THREAD

**Issue by Paulsurinder** [TestingReach/MVP-V1#16]
Invitation-User send invite to any user, checkbox will be uncheck after sending invitation so that if user try to send invitation to other users, it will not block invitation due to 24 hrs condition

**Comment by pankajtrantor1** [comment]
@Paulsurinder sure this would be automatically  resolved once the uncheck bug is resolved

**Comment by Paulsurinder** [comment]
This issue was moved to reachable-dev/Reachable-Salesforce#7
