### ISSUE TITLE
Pagination-If User on first page and click on First button application showing last page, here First and Previous button should be disable in case user is on first page same as for Last Page Next and Last button should be disabled

### ISSUE THREAD

**Issue by Paulsurinder** [TestingReach/MVP-V1#18]
Pagination-If User on first page and click on First button application showing last page, here First and Previous button should be disable in case user is on first page same as for Last Page Next and Last button should be disabled

**Comment by pankajtrantor1** [comment]
Ok this is accepted

**Comment by Paulsurinder** [comment]
This issue was moved to reachable-dev/Reachable-Salesforce#5
