### ISSUE TITLE
Pagination-There should browsing icon while loading second page i notice there is some latency to load page or we can also cover with shadow in execution time so that user not able to press any other button while request execution

### ISSUE THREAD

**Issue by Paulsurinder** [TestingReach/MVP-V1#19]
Pagination-There should browsing icon while loading second page i notice there is some latency to load page or we can also cover with shadow in execution time so that user not able to press any other button while request execution

**Comment by pankajtrantor1** [comment]
This would be enhancement to UI , not a bug for MVP

**Comment by Paulsurinder** [comment]
That is low severity usability bug not UI enhancement because there is nothing that shows processing is going on

**Comment by Paulsurinder** [comment]
This issue was moved to reachable-dev/Reachable-Salesforce#4
