### ISSUE TITLE
Code Review - Admin Module 

### ISSUE THREAD

**Issue by pankajtrantor1** [TestingReach/MVP-V1#22]
Attached are all the findings from the code review, open them in notepad++ for better readability. Please incorporate these changes and Please refer the code at the org (pankajv@trantorinc.com/Trantor@1) for better understanding .

Let me know for any questions you may have.
[Code Review for Admin Module.txt](https://github.com/TestingReach/MVP-V1/files/494649/Code.Review.for.Admin.Module.txt)

**Comment by Paulsurinder** [comment]
This issue was moved to reachable-dev/Reachable-Salesforce#1
